# Generated by Django 5.2.8 on 2025-11-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
