# Generated by Django 5.1.5 on 2025-11-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='is_active',
        ),
        migrations.AddField(
            model_name='stage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='courses.category'),
        ),
        migrations.AddField(
            model_name='stage',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='courses.subcategory'),
        ),
    ]
