# Generated by Django 5.1.5 on 2025-11-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_stage_is_active_stage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='courses.stage'),
        ),
    ]
