# Generated by Django 5.1.5 on 2025-11-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_level_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
