# Generated by Django 5.1.5 on 2025-11-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='courses.category'),
        ),
    ]
