# Generated by Django 5.1.5 on 2025-11-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_subject_level_subject_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Stage',
            new_name='Stages',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject'),
        ),
    ]
