# Generated by Django 5.1.5 on 2025-11-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_stage_subject_stages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='courses.subcategory'),
        ),
    ]
